tp: tp.tex
	make clean
	pdflatex tp.tex
	bibtex tp
	pdflatex tp.tex
	pdflatex tp.tex

clean:
	rm -f *.aux
	rm -f *.log
	rm -f *.synctex.gz
	rm -f *.out
	rm -f *.xml
	rm -f *.bcf
	rm -f *.blg
	rm -f *.bbl
	rm -f tp-blx.bib
	rm -f *.toc
